유사 서비스 분석 및 보완점, 오픈소스
hs-1971322-subinJang/OPENSOURCE8_166 pull request #4
Opened 2022-11-13 04:44 UTC by hs-1971240-jinhokim

유사 서비스 분석 및 보완점 그리고 오픈소스 링크 추가하였습니다.

2022-11-13 05:53 UTC, gesal03 approved these changes
좋은 유사 서비스 분석이었습니다.

2022-11-14 08:41 UTC, xogk1128 reviewed
저희가 하고자 하는 서비스와 유사한 서비스 분석이었습니다.

2022-11-14 08:41 UTC, longrunbiin requested changes
유사 서비스 사진과 함께 좀더 자세한 설명있으면 좋겠습니다,

2022-11-14 08:45 UTC, xogk1128 approved these changes
저희가 하고자 하는 서비스와 유사한 서비스 분석이었습니다.

2022-11-19 15:19 UTC, hs-1971322-subinJang approved these changes

2022-11-19 15:20 UTC, merged